# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='streamListen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
