# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('associated_user_ids', models.TextField()),
                ('timestamp', models.IntegerField(default=0)),
                ('info', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='streamListen',
        ),
    ]
