# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0002_auto_20170429_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('target', models.BooleanField(default=False)),
                ('delay', models.IntegerField(default=0)),
                ('url', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='stream',
            name='associated_user_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stream',
            name='user_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
